[[redirects]]
  from = "https://shirako-mamu.netlify.app"
  to = "https://shirako.dev"
  status = 301
  force = true

[[redirects]]
  from = "https://shirako-mamu.netlify.app/*"
  to = "https://shirako.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self';
      style-src 'self';
      img-src 'self'
    '''
    Strict-Transport-Security = '''
      max-age=63072000;
      includeSubDomains;
      preload
    '''
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = '''
      accelerometer=(),
      ambient-light-sensor=(),
      autoplay=(),
      camera=(),
      encrypted-media=(),
      fullscreen=(),
      geolocation=(),
      gyroscope=(),
      magnetometer=(),
      microphone=(),
      midi=(),
      payment=(),
      picture-in-picture=(),
      speaker=(),
      usb=(),
      vibrate=(),
      vr=()
    '''
    Referrer-Policy = "no-referrer"
    Expect-CT = "enforce, max-age=300"
    Cross-Origin-Embedder-Policy = "unsafe-none|require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
